language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - travis_retry composer self-update

install:
  - curl http://get.sensiolabs.org/php-cs-fixer.phar -o php-cs-fixer.phar
  - curl http://get.sensiolabs.org/security-checker.phar -o security-checker.phar
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer --diff --dry-run -vv fix
  - php -n security-checker.phar security:check --format=simple

after_script:
  - if [[ $TRAVIS_PHP_VERSION = "5.4" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TRAVIS_PHP_VERSION = "5.4" ]]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover; fi
